backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "artists"
    label: "Artists"
    folder: "src/pages/artists"
    slug: "{{name}}"
    identifier_field: name
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "artist-page"
        }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: false
        }
      - {
          label: "Accepts Commissions",
          name: "acceptsCommissions",
          widget: "string",
          required: false
        }
      - { label: "Media", name: "media", widget: "string", required: false }
      - {
          label: "Specialty",
          name: "specialty",
          widget: "string",
          required: false
        }
      - { label: "Email", name: "email", widget: "string", required: false }
      - {
          label: "Artist Image",
          name: "artistimage",
          widget: image,
          required: false
        }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false
        }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post"
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page"
            }
          - { label: Title, name: title, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page"
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
